spring.application.name=user

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/ms-user
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver

springdoc.swagger-ui.path="swagger-ui/html"